insert into twits (user_id,text,timestamp)
values
(2,'Patton Oswalt is not as funny as Louis CK.',now()),
(5,'Nerds rule, jocks drool.',now()),
(8,'Snap, crackle, pop.',now()),
(2,'The sky is as dark as my soul.',now()),
(6,'Check out my new Lamborghini.',now()),
(10,'Plane or plain?',now()),
(11,'TGIF! Time to catch up on my sleep!',now()),
(7,'WAKKA WAKKA WAKKA.',now()),
(12,'Semicolons are overrated.',now()),
(4,'LOTS AND LOTS O TWITS MAN',now()),
(4,'Wow, I wish twitter was as cool as twiter',now()),
(4,'Kim Kardashian.',now()),
(9,'GODZILLA',now()),
(9,'Ninjas, man. So many ninjas.',now()),
(9,'I enjoy fencing',now()),
(1,'It is TWIT not TWAT',now()),
(3,'Haiku is for chumps.',now()),
(10,'What a beautiful day.',now()),
(6,'Team COBRA is the balls.',now()),
(4,'The surf forecast is freaking scary.',now()),
(9,'The rain in spain falls mainly on the plain, the rain in Portla',now()),
(3,'TGIF! Bring on the adult beverages!',now()),
(1,'I heart twiter.',now()),
(1,':-) :-) :-) :-)',now()),
(1,'My name is steve and I believe.',now()),
(1,'What do I put in my coffee? STEVE-IA!',now()),
(1,'I did not have relations with that database!',now());